export const inputFormats = {
  markdown: { label: "markdown", binary: false },
  native: { label: "native", binary: false },
  json: { label: "json", binary: false },
  markdown_strict: { label: "markdown_strict", binary: false },
  markdown_phpextra: { label: "markdown_phpextra", binary: false },
  markdown_github: { label: "markdown_github", binary: false },
  markdown_mmd: { label: "markdown_mmd", binary: false },
  commonmark: { label: "commonmark", binary: false },
  commonmark_x: { label: "commonmark_x", binary: false },
  creole: { label: "creole", binary: false },
  dokuwiki: { label: "dokuwiki", binary: false },
  gfm: { label: "gfm", binary: false },
  rst: { label: "rst", binary: false },
  mediawiki: { label: "mediawiki", binary: false },
  vimwiki: { label: "vimwiki", binary: false },
  docbook: { label: "docbook", binary: false },
  opml: { label: "opml", binary: false },
  org: { label: "org", binary: false },
  textile: { label: "textile", binary: false },
  html: { label: "html", binary: false },
  bits: { label: "bits", binary: false },
  jats: { label: "jats", binary: false },
  jira: { label: "jira", binary: false },
  latex: { label: "latex", binary: false },
  haddock: { label: "haddock", binary: false },
  twiki: { label: "twiki", binary: false },
  tikiwiki: { label: "tikiwiki", binary: false },
  docx: { label: "docx", binary: true },
  odt: { label: "odt", binary: true },
  t2t: { label: "t2t", binary: false },
  epub: { label: "epub", binary: true },
  muse: { label: "muse", binary: false },
  man: { label: "man", binary: false },
  fb2: { label: "fb2", binary: false },
  ipynb: { label: "ipynb", binary: false },
  csv: { label: "csv", binary: false },
  tsv: { label: "tsv", binary: false },
  csljson: { label: "csljson", binary: false },
  bibtex: { label: "bibtex", binary: false },
  biblatex: { label: "biblatex", binary: false },
  endnotexml: { label: "endnotexml", binary: false },
  ris: { label: "ris", binary: false },
  rtf: { label: "rtf", binary: false },
};

export const outputFormats = {
  html: { label: "HTML", binary: false, ext: ".html", mime: "text/html" },
  native: { label: "Native Haskell", binary: false },
  json: {
    label: "json",
    binary: false,
    ext: ".json",
    mime: "application/json",
  },
  docx: {
    label: "docx",
    binary: true,
    ext: ".docx",
    mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  },
  odt: {
    label: "odt",
    binary: true,
    ext: ".odt",
    mime: "application/vnd.oasis.opendocument.text",
  },
  pptx: {
    label: "pptx",
    binary: true,
    ext: ".pptx",
    mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  },
  epub: {
    label: "epub",
    binary: true,
    ext: ".epub",
    mime: "application/epub+zip",
  },
  epub2: {
    label: "epub2",
    binary: true,
    ext: ".epub",
    mime: "application/epub+zip",
  },
  epub3: {
    label: "epub3",
    binary: true,
    ext: ".epub",
    mime: "application/epub+zip",
  },
  fb2: { label: "fb2", binary: false, ext: ".fb2", mime: "text/fb2+xml" },
  ipynb: {
    label: "ipynb",
    binary: false,
    ext: ".ipynb",
    mime: "application/x-ipynb+json",
  },
  html4: { label: "html4", binary: false, ext: ".html", mime: "text/html" },
  html5: { label: "html5", binary: false, ext: ".html", mime: "text/html" },
  icml: {
    label: "icml",
    binary: false,
    ext: ".icml",
    mime: "application/x-indesign",
  },
  s5: { label: "s5", binary: false, ext: ".html", mime: "text/html" },
  slidy: { label: "slidy", binary: false, ext: ".html", mime: "text/html" },
  slideous: {
    label: "slideous",
    binary: false,
    ext: ".html",
    mime: "text/html",
  },
  dzslides: {
    label: "dzslides",
    binary: false,
    ext: ".html",
    mime: "text/html",
  },
  revealjs: {
    label: "revealjs",
    binary: false,
    ext: ".html",
    mime: "text/html",
  },
  docbook: {
    label: "docbook",
    binary: false,
    ext: ".dbk",
    mime: "application/docbook+xml",
  },
  docbook4: {
    label: "docbook4",
    binary: false,
    ext: ".dbk",
    mime: "application/docbook+xml",
  },
  docbook5: {
    label: "docbook5",
    binary: false,
    ext: ".dbk",
    mime: "application/docbook+xml",
  },
  jats: { label: "jats", binary: false, ext: ".xml", mime: "application/xml" },
  jats_articleauthoring: {
    label: "jats_articleauthoring",
    binary: false,
    ext: ".xml",
    mime: "application/xml",
  },
  jats_publishing: {
    label: "jats_publishing",
    binary: false,
    ext: ".xml",
    mime: "application/xml",
  },
  jats_archiving: {
    label: "jats_archiving",
    binary: false,
    ext: ".xml",
    mime: "application/xml",
  },
  jira: { label: "jira", binary: false, ext: ".jira", mime: "text/plain" },
  opml: { label: "opml", binary: false, ext: ".opem", mime: "application/xml" },
  opendocument: {
    label: "opendocument",
    binary: false,
    ext: ".odt",
    mime: "application/vnd.oasis.opendocument.text",
  },
  latex: {
    label: "latex",
    binary: false,
    ext: ".tex",
    mime: "application/x-latex",
  },
  beamer: {
    label: "beamer",
    binary: false,
    ext: ".tex",
    mime: "application/x-latex",
  },
  context: {
    label: "context",
    binary: false,
    ext: ".tex",
    mime: "application/x-tex",
  },
  texinfo: {
    label: "texinfo",
    binary: false,
    ext: ".texi",
    mime: "application/x-texinfo",
  },
  man: { label: "man", binary: false, ext: ".man", mime: "text/troff" },
  ms: { label: "ms", binary: false, ext: ".ms", mime: "text/troff" },
  markdown: {
    label: "markdown",
    binary: false,
    ext: ".md",
    mime: "text/x-markdown",
  },
  markdown_strict: {
    label: "markdown_strict",
    binary: false,
    ext: ".md",
    mime: "text/x-markdown",
  },
  markdown_phpextra: {
    label: "markdown_phpextra",
    binary: false,
    ext: ".md",
    mime: "text/x-markdown",
  },
  markdown_github: {
    label: "markdown_github",
    binary: false,
    ext: ".md",
    mime: "text/x-markdown",
  },
  markdown_mmd: {
    label: "markdown_mmd",
    binary: false,
    ext: ".md",
    mime: "text/x-markdown",
  },
  plain: { label: "plain", binary: false, ext: ".txt", mime: "text/plain" },
  rst: { label: "rst", binary: false, ext: ".rst", mime: "text/x-rst" },
  mediawiki: {
    label: "mediawiki",
    binary: false,
    ext: ".txt",
    mime: "text/plain",
  },
  dokuwiki: {
    label: "dokuwiki",
    binary: false,
    ext: ".txt",
    mime: "text/plain",
  },
  xwiki: { label: "xwiki", binary: false, ext: ".txt", mime: "text/plain" },
  zimwiki: { label: "zimwiki", binary: false, ext: ".txt", mime: "text/plain" },
  textile: {
    label: "textile",
    binary: false,
    ext: ".textile",
    mime: "text/x-textile",
  },
  typst: { label: "typst", binary: false, ext: ".txt", mime: "text/plain" },
  rtf: { label: "rtf", binary: false, ext: ".rtf", mime: "application/rtf" },
  org: { label: "org", binary: false, ext: ".org", mime: "text/x-org" },
  asciidoc: {
    label: "asciidoc",
    binary: false,
    ext: ".adoc",
    mime: "text/asciidoc",
  },
  asciidoctor: {
    label: "asciidoctor",
    binary: false,
    ext: ".adoc",
    mime: "text/asciidoc",
  },
  asciidoc_legacy: {
    label: "asciidoc_legacy",
    binary: false,
    ext: ".adoc",
    mime: "text/asciidoc",
  },
  haddock: { label: "haddock", binary: false, ext: ".txt", mime: "text/plain" },
  commonmark: {
    label: "commonmark",
    binary: false,
    ext: ".md",
    mime: "text/x-markdown",
  },
  commonmark_x: {
    label: "commonmark_x",
    binary: false,
    ext: ".md",
    mime: "text/x-markdown",
  },
  gfm: { label: "gfm", binary: false, ext: ".md", mime: "text/x-markdown" },
  tei: {
    label: "tei",
    binary: false,
    ext: ".tei",
    mime: "application/tei+xml",
  },
  muse: { label: "muse", binary: false, ext: ".muse", mime: "text/plain" },
  csljson: {
    label: "csljson",
    binary: false,
    ext: ".json",
    mime: "application/json",
  },
  bibtex: {
    label: "bibtex",
    binary: false,
    ext: ".bib",
    mime: "application/x-bibtex-text-file",
  },
  biblatex: {
    label: "biblatex",
    binary: false,
    ext: ".bib",
    mime: "application/x-bibtex-text-file",
  },
  markua: { label: "markua", binary: false, ext: ".txt", mime: "text/plain" },
  chunkedhtml: {
    label: "chunkedhtml",
    binary: true,
    ext: ".zip",
    mime: "application/zip",
  },
};
