name: Build and deploy Pandoc application

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build-pandoc-wasm:
    name: Build pandoc-wasm
    runs-on: self-hosted
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup git submodules
        run: make submodules
      - name: Setup Docker container
        run: make docker-container
      - name: Build pandoc-wasm
        run: make
      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: www
          retention-days: 1
      - name: Publish to npm
        if: "!contains(github.ref_name, 'main')"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access=public
  deploy-github-pages:
    if: "contains(github.ref_name, 'main')"
    needs: build-pandoc-wasm
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
